//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tune
    {
        public int TuneID { get; set; }
        public string Title { get; set; }
        public string Album { get; set; }
        public string Artist { get; set; }
        public Nullable<int> Year { get; set; }
        public string Comment { get; set; }
        public string Genre { get; set; }
        public string VirtualPath { get; set; }
    }
}
